import { Language } from "./types";

export const LANGUAGES: { code: Language; label: string; nativeLabel: string; prompt: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', prompt: "How can I help you today?" },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी', prompt: "आज मैं आपकी कैसे मदद कर सकता हूँ?" },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', prompt: "मी तुम्हाला कशी मदत करू शकतो?" },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', prompt: "ఈ రోజు నేను మీకు ఎలా సహాయపడగలను?" },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', prompt: "இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?" },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', prompt: "আজ আমি আপনাকে কিভাবে সাহায্য করতে পারি?" },
];

export const MOCK_LISTINGS = [
  {
    id: '1',
    farmerId: 'f1',
    farmerName: 'Ramesh Kumar',
    cropName: 'Onion (Pyaz)',
    cropNameEnglish: 'Onion',
    quantity: 500,
    price: 25,
    location: 'Nashik, Maharashtra',
    description: 'Fresh red onions, harvested yesterday.',
    timestamp: Date.now() - 100000,
  },
  {
    id: '2',
    farmerId: 'f2',
    farmerName: 'Suresh Patil',
    cropName: 'Wheat (Gehu)',
    cropNameEnglish: 'Wheat',
    quantity: 1000,
    price: 22,
    location: 'Pune, Maharashtra',
    description: 'High quality Lokwan wheat.',
    timestamp: Date.now() - 200000,
  },
];

export const TRANSLATIONS = {
  en: {
    welcome: "Namaste",
    roleFarmer: "Farmer (Annadata)",
    roleBuyer: "Buyer (Vyapari)",
    marketInsight: "Market Insight",
    createListing: "List New Crop",
    myListings: "My Listings",
    inbox: "Inbox",
    cropName: "Crop Name",
    quantity: "Quantity (kg)",
    price: "Price (₹/kg)",
    location: "Location",
    description: "Description",
    save: "Save Listing",
    update: "Update Listing",
    cancel: "Cancel",
    edit: "Edit",
    chat: "Chat",
    call: "Call",
    voicePlaceholder: "Tap to speak...",
    negotiate: "Negotiate / Buy",
    buy: "Buy",
    trend: "Trend",
    noListings: "No listings yet.",
    messages: "Messages",
    messageFrom: "Message from",
    tapToSpeak: "Tap to speak",
    voicePromptCreate: "I want to sell 500kg of Onions...",
    voicePromptEdit: "Change price to 30...",
    findCrops: "Find fresh crops directly from farmers",
    mandiTitle: "SpeakHarvest Marketplace",
    negotiationTitle: "Negotiation",
    typeMessage: "Type a message...",
    send: "Send",
    profile: "Profile",
    unknown: "Unknown",
    // New additions
    selectLanguage: "Select Language",
    whoAreYou: "Who are you?",
    sellCropsDesc: "I want to sell crops",
    buyCropsDesc: "I want to buy crops",
    loginTitle: "Login",
    loginSubtitle: "Enter mobile number to continue",
    enterPhonePlaceholder: "+91 98765 43210",
    otpPlaceholder: "Enter OTP (Any 4 digits)",
    verifyLogin: "Verify & Login",
    secureText: "Secure & Encrypted",
    // Voice Modal
    voiceModalWelcome: "Welcome! Please tell me your full name.",
    voiceModalTitle: "Welcome!",
    voiceModalSubtitle: "Let's get to know each other",
    voiceModalLabel: "Your Full Name",
    voiceModalPlaceholder: "Type your name here...",
    voiceModalMicHint: "Tap mic or just speak to enter name",
    voiceModalSave: "Save & Continue"
  },
  hi: {
    welcome: "नमस्ते",
    roleFarmer: "किसान (अन्नदाता)",
    roleBuyer: "खरीदार (व्यापारी)",
    marketInsight: "बाजार की जानकारी",
    createListing: "नई फसल बेचें",
    myListings: "मेरी फसलें",
    inbox: "संदेश",
    cropName: "फसल का नाम",
    quantity: "मात्रा (किलो)",
    price: "कीमत (₹/किलो)",
    location: "स्थान",
    description: "विवरण",
    save: "फसल सूची में डालें",
    update: "अपडेट करें",
    cancel: "रद्द करें",
    edit: "बदलें",
    chat: "बातचीत",
    call: "कॉल करें",
    voicePlaceholder: "बोलने के लिए टैप करें...",
    negotiate: "मोलभाव / खरीदें",
    buy: "खरीदें",
    trend: "रुझान",
    noListings: "अभी तक कोई फसल नहीं है।",
    messages: "संदेश",
    messageFrom: "का संदेश",
    tapToSpeak: "बोलने के लिए टैप करें",
    voicePromptCreate: "मैं 500 किलो प्याज बेचना चाहता हूं...",
    voicePromptEdit: "कीमत 30 रुपये कर दो...",
    findCrops: "किसानों से सीधे ताजी फसलें प्राप्त करें",
    mandiTitle: "मंडी बाज़ार",
    negotiationTitle: "मोलभाव",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    unknown: "अज्ञात",
    // New additions
    selectLanguage: "भाषा चुनें",
    whoAreYou: "आप कौन हैं?",
    sellCropsDesc: "मैं फसल बेचना चाहता हूँ",
    buyCropsDesc: "मैं फसल खरीदना चाहता हूँ",
    loginTitle: "लॉगिन",
    loginSubtitle: "आगे बढ़ने के लिए मोबाइल नंबर दर्ज करें",
    enterPhonePlaceholder: "+91 98765 43210",
    otpPlaceholder: "OTP दर्ज करें (कोई भी 4 अंक)",
    verifyLogin: "सत्यापित करें और लॉगिन करें",
    secureText: "सरक्षित और एन्क्रिप्टेड",
    // Voice Modal
    voiceModalWelcome: "नमस्ते! कृपया अपना पूरा नाम बताएं।",
    voiceModalTitle: "आपका स्वागत है!",
    voiceModalSubtitle: "आइए एक दूसरे को जानें",
    voiceModalLabel: "आपका पूरा नाम",
    voiceModalPlaceholder: "यहां नाम लिखें...",
    voiceModalMicHint: "बोलकर बताने के लिए माइक पर क्लिक करें",
    voiceModalSave: "सहेजें और आगे बढ़ें"
  },
  mr: {
    welcome: "नमस्कार",
    roleFarmer: "शेतकरी (अन्नदाता)",
    roleBuyer: "खरेदीदार (व्यापारी)",
    marketInsight: "बाजार भाव",
    createListing: "नवीन पीक विक्री",
    myListings: "माझी पिके",
    inbox: "संदेश",
    cropName: "पिकाचे नाव",
    quantity: "प्रमाण (किलो)",
    price: "भाव (₹/किलो)",
    location: "स्थान",
    description: "वर्णन",
    save: "यादीत टाका",
    update: "अपडेट करा",
    cancel: "रद्द करा",
    edit: "संपादित करा",
    chat: "चर्चा",
    call: "कॉल करा",
    voicePlaceholder: "बोलण्यासाठी टॅप करा...",
    negotiate: "वाटाघाटी / खरेदी",
    buy: "खरेदी करा",
    trend: "कल",
    noListings: "अद्याप कोणतीही पिके नाहीत.",
    messages: "संदेश",
    messageFrom: "यांचा संदेश",
    tapToSpeak: "बोलण्यासाठी टॅप करा",
    voicePromptCreate: "मला 500 किलो कांदा विकायचा आहे...",
    voicePromptEdit: "भाव 30 रुपये करा...",
    findCrops: "थेट शेतकऱ्यांकडून ताजी पिके मिळवा",
    mandiTitle: "मंडी बाजारपेठ",
    negotiationTitle: "वाटाघाटी",
    typeMessage: "संदेश लिहा...",
    send: "पाठवा",
    unknown: "अज्ञात",
    // New additions
    selectLanguage: "भाषा निवडा",
    whoAreYou: "तुम्ही कोण आहात?",
    sellCropsDesc: "मला पिके विकायची आहेत",
    buyCropsDesc: "मला पिके खरेदी करायची आहेत",
    loginTitle: "लॉगिन",
    loginSubtitle: "पुढे जाण्यासाठी मोबाईल नंबर टाका",
    enterPhonePlaceholder: "+91 98765 43210",
    otpPlaceholder: "OTP टाका (कोणतेही 4 अंक)",
    verifyLogin: "पडताळणी करा आणि लॉगिन करा",
    secureText: "सुरक्षित आणि एनक्रिप्टेड",
    // Voice Modal
    voiceModalWelcome: "नमस्कार! कृपया तुमचे पूर्ण नाव सांगा.",
    voiceModalTitle: "स्वागत आहे!",
    voiceModalSubtitle: "चला एकमेकांना ओळखूया",
    voiceModalLabel: "तुमचे पूर्ण नाव",
    voiceModalPlaceholder: "इथे नाव टाईप करा...",
    voiceModalMicHint: "बोलण्यासाठी माइकवर टॅप करा",
    voiceModalSave: "सेव्ह करा आणि पुढे जा"
  },
  te: {
    welcome: "నమస్కారం",
    roleFarmer: "రైతు (అన్నదాత)",
    roleBuyer: "కొనుగోలుదారు (వ్యాపారి)",
    marketInsight: "మార్కెట్ సమాచారం",
    createListing: "కొత్త పంటను అమ్మండి",
    myListings: "నా పంటలు",
    inbox: "సందేశాలు",
    cropName: "పంట పేరు",
    quantity: "పరిమాణం (kg)",
    price: "ధర (₹/kg)",
    location: "ప్రాంతం",
    description: "వివరణ",
    save: "జాబితాలో చేర్చు",
    update: "నవీకరించు",
    cancel: "రద్దు చేయి",
    edit: "సవరించు",
    chat: "చాట్",
    call: "కాల్",
    voicePlaceholder: "మాట్లాడటానికి నొక్కండి...",
    negotiate: "బేరసారాలు / కొనండి",
    buy: "కొనండి",
    trend: "ట్రెండ్",
    noListings: "ఇంకా పంటలు లేవు.",
    messages: "సందేశాలు",
    messageFrom: "నుండి సందేశం",
    tapToSpeak: "మాట్లాడటానికి నొక్కండి",
    voicePromptCreate: "నేను 500 కిలోల ఉల్లిపాయలు అమ్మాలనుకుంటున్నాను...",
    voicePromptEdit: "ధర 30 రూపాయలకు మార్చండి...",
    findCrops: "తాజా పంటలను నేరుగా రైతుల నుండి పొందండి",
    mandiTitle: "మండి మార్కెట్",
    negotiationTitle: "బేరసారాలు",
    typeMessage: "సందేశం టైప్ చేయండి...",
    send: "పంపు",
    unknown: "తెలియదు",
    // New additions
    selectLanguage: "భాషను ఎంచుకోండి",
    whoAreYou: "మీరు ఎవరు?",
    sellCropsDesc: "నేను పంటలు అమ్మాలనుకుంటున్నాను",
    buyCropsDesc: "నేను పంటలు కొనాలనుకుంటున్నాను",
    loginTitle: "లాగిన్",
    loginSubtitle: "కొనసాగడానికి మొబైల్ నంబర్‌ను నమోదు చేయండి",
    enterPhonePlaceholder: "+91 98765 43210",
    otpPlaceholder: "OTP నమోదు చేయండి (ఏవైనా 4 అంకెలు)",
    verifyLogin: "ధృవీకరించండి & లాగిన్ అవ్వండి",
    secureText: "సురక్షితమైన మరియు ఎన్‌క్రిప్ట్ చేయబడింది",
    // Voice Modal
    voiceModalWelcome: "నమస్కారం! దయచేసి మీ పూర్తి పేరు చెప్పండి.",
    voiceModalTitle: "స్వాగతం!",
    voiceModalSubtitle: "ఒకరినొకరు తెలుసుకుందాం",
    voiceModalLabel: "మీ పూర్తి పేరు",
    voiceModalPlaceholder: "మీ పేరు ఇక్కడ టైప్ చేయండి...",
    voiceModalMicHint: "మాట్లాడటానికి మైక్‌పై నొక్కండి",
    voiceModalSave: "సేవ్ చేసి కొనసాగించండి"
  },
  ta: {
    welcome: "வணக்கம்",
    roleFarmer: "விவசாயி (அன்னதாத்தா)",
    roleBuyer: "வாங்குபவர் (வியாபாரி)",
    marketInsight: "சந்தை நிலவரம்",
    createListing: "புதிய பயிரை விற்க",
    myListings: "என் பயிர்கள்",
    inbox: "செய்திகள்",
    cropName: "பயிர் பெயர்",
    quantity: "அளவு (kg)",
    price: "விலை (₹/kg)",
    location: "இடம்",
    description: "விளக்கம்",
    save: "பட்டியலிடு",
    update: "புதுப்பி",
    cancel: "ரத்து செய்",
    edit: "திருத்து",
    chat: "உரையாடல்",
    call: "அழைப்பு",
    voicePlaceholder: "பேச தட்டவும்...",
    negotiate: "பேரம் / வாங்கு",
    buy: "வாங்கு",
    trend: "போக்கு",
    noListings: "பயிர்கள் எதுவும் இல்லை.",
    messages: "செய்திகள்",
    messageFrom: "விடமிருந்து செய்தி",
    tapToSpeak: "பேச தட்டவும்",
    voicePromptCreate: "நான் 500 கிலோ வெங்காயம் விற்க விரும்புகிறேன்...",
    voicePromptEdit: "விலையை 30 ஆக மாற்றவும்...",
    findCrops: "விவசாயிகளிடமிருந்து நேரடியாக பயிர்களைப் பெறுங்கள்",
    mandiTitle: "மண்டி சந்தை",
    negotiationTitle: "பேரம்",
    typeMessage: "செய்தியை தட்டச்சு செய்யவும்...",
    send: "அனுப்பு",
    unknown: "தெரியவில்லை",
    // New additions
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    whoAreYou: "நீங்கள் யார்?",
    sellCropsDesc: "நான் பயிர்களை விற்க விரும்புகிறேன்",
    buyCropsDesc: "நான் பயிர்களை வாங்க விரும்புகிறேன்",
    loginTitle: "உள்நுழைய",
    loginSubtitle: "தொடர மொபைல் எண்ணை உள்ளிடவும்",
    enterPhonePlaceholder: "+91 98765 43210",
    otpPlaceholder: "OTP ஐ உள்ளிடவும் (ஏதேனும் 4 இலக்கங்கள்)",
    verifyLogin: "சரிபார்த்து உள்நுழையவும்",
    secureText: "பாதுகாப்பான மற்றும் மறைகுறியாக்கப்பட்ட",
    // Voice Modal
    voiceModalWelcome: "வணக்கம்! உங்கள் முழு பெயரைச் சொல்லுங்கள்.",
    voiceModalTitle: "வரவேற்கிறோம்!",
    voiceModalSubtitle: "ஒருவருக்கொருவர் தெரிந்து கொள்வோம்",
    voiceModalLabel: "உங்கள் முழு பெயர்",
    voiceModalPlaceholder: "உங்கள் பெயரை இங்கே தட்டச்சு செய்யவும்...",
    voiceModalMicHint: "பேச மைக்கைத் தட்டவும்",
    voiceModalSave: "சேமித்து தொடரவும்"
  },
  bn: {
    welcome: "স্বাগতম",
    roleFarmer: "কৃষক (অন্নদাতা)",
    roleBuyer: "ক্রেতা (ব্যবসায়ী)",
    marketInsight: "বাজারের অন্তর্দৃষ্টি",
    createListing: "নতুন ফসল তালিকাভুক্ত করুন",
    myListings: "আমার তালিকা",
    inbox: "ইনবক্স",
    cropName: "ফসলের নাম",
    quantity: "পরিমাণ (কেজি)",
    price: "দাম (₹/কেজি)",
    location: "অবস্থান",
    description: "বিবরণ",
    save: "তালিকাভুক্ত করুন",
    update: "আপডেট করুন",
    cancel: "বাতিল করুন",
    edit: "সম্পাদনা করুন",
    chat: "চ্যাট",
    call: "কল করুন",
    voicePlaceholder: "কথা বলতে ট্যাপ করুন...",
    negotiate: "দরদাম / কিনুন",
    buy: "কিনুন",
    trend: "প্রবণতা",
    noListings: "এখনও কোন ফসল তালিকাভুক্ত নেই।",
    messages: "বার্তা",
    messageFrom: "এর থেকে বার্তা",
    tapToSpeak: "কথা বলতে ট্যাপ করুন",
    voicePromptCreate: "আমি ৫০০ কেজি পেঁয়াজ বিক্রি করতে চাই...",
    voicePromptEdit: "দাম ৩০ টাকা করুন...",
    findCrops: "সরাসরি কৃষকদের কাছ থেকে তাজা ফসল পান",
    mandiTitle: "মন্ডি মার্কেটপ্লেস",
    negotiationTitle: "দরদামে",
    typeMessage: "একটি বার্তা টাইপ করুন...",
    send: "পাঠান",
    unknown: "অজানা",
    selectLanguage: "ভাষা নির্বাচন করুন",
    whoAreYou: "আপনি কে?",
    sellCropsDesc: "আমি ফসল বিক্রি করতে চাই",
    buyCropsDesc: "আমি ফসল কিনতে চাই",
    loginTitle: "লগ ইন",
    loginSubtitle: "চালিয়ে যেতে মোবাইল নম্বর লিখুন",
    enterPhonePlaceholder: "+৯১ ৯৮৭৬৫ ৪৩২১০",
    otpPlaceholder: "OTP লিখুন (যেকোনো ৪ সংখ্যা)",
    verifyLogin: "যাচাই করুন এবং লগ ইন করুন",
    secureText: "সুরক্ষিত এবং এনক্রিপ্ট করা",
    // Voice Modal
    voiceModalWelcome: "স্বাগতম! আপনার পুরো নাম বলুন।",
    voiceModalTitle: "স্বাগতম!",
    voiceModalSubtitle: "আসুন একে অপরকে চিনি",
    voiceModalLabel: "আপনার পুরো নাম",
    voiceModalPlaceholder: "এখানে আপনার নাম টাইপ করুন...",
    voiceModalMicHint: "কথা বলতে মাইকে ট্যাপ করুন",
    voiceModalSave: "সংরক্ষণ করুন এবং চালিয়ে যান"
  }
};
